const platformLabels = {
  bilibili: 'B站',
  douyin: '抖音'
}

const rawUpdatePlanRows = [
  {
    "groupName": "内容小组",
    "platform": "douyin",
    "accountType": "重点账号",
    "owner": "",
    "account": "花无缺",
    "contentDirection": "游戏深度体验/解说向",
    "durationText": "2-3min",
    "videoLengthType": "long",
    "benchmarkAccounts": "",
    "monthlyTarget": 2,
    "monthlyTotal": 10,
    "note": ""
  },
  {
    "groupName": "内容小组",
    "platform": "douyin",
    "accountType": "重点账号",
    "owner": "",
    "account": "花无缺",
    "contentDirection": "短视频（热点/常规游戏向内容）",
    "durationText": "1-2min",
    "videoLengthType": "short",
    "benchmarkAccounts": "",
    "monthlyTarget": 6,
    "monthlyTotal": 0,
    "note": ""
  },
  {
    "groupName": "内容小组",
    "platform": "douyin",
    "accountType": "重点账号",
    "owner": "",
    "account": "花无缺",
    "contentDirection": "非游热梗",
    "durationText": "1-2min",
    "videoLengthType": "short",
    "benchmarkAccounts": "",
    "monthlyTarget": 2,
    "monthlyTotal": 0,
    "note": ""
  },
  {
    "groupName": "内容小组",
    "platform": "douyin",
    "accountType": "重点账号",
    "owner": "",
    "account": "最游话说",
    "contentDirection": "游戏深度体验/解说向",
    "durationText": "2-3min",
    "videoLengthType": "long",
    "benchmarkAccounts": "",
    "monthlyTarget": 2,
    "monthlyTotal": 10,
    "note": ""
  },
  {
    "groupName": "内容小组",
    "platform": "douyin",
    "accountType": "重点账号",
    "owner": "",
    "account": "最游话说",
    "contentDirection": "短视频（热点/常规游戏向内容）",
    "durationText": "1-2min",
    "videoLengthType": "short",
    "benchmarkAccounts": "",
    "monthlyTarget": 5,
    "monthlyTotal": 0,
    "note": ""
  },
  {
    "groupName": "内容小组",
    "platform": "douyin",
    "accountType": "重点账号",
    "owner": "",
    "account": "最游话说",
    "contentDirection": "非游热梗",
    "durationText": "1-2min",
    "videoLengthType": "short",
    "benchmarkAccounts": "",
    "monthlyTarget": 3,
    "monthlyTotal": 0,
    "note": ""
  },
  {
    "groupName": "内容小组",
    "platform": "douyin",
    "accountType": "重点账号",
    "owner": "",
    "account": "报告砖家",
    "contentDirection": "游戏深度体验/解说向",
    "durationText": "2-3min",
    "videoLengthType": "long",
    "benchmarkAccounts": "",
    "monthlyTarget": 4,
    "monthlyTotal": 10,
    "note": ""
  },
  {
    "groupName": "内容小组",
    "platform": "douyin",
    "accountType": "重点账号",
    "owner": "",
    "account": "报告砖家",
    "contentDirection": "短视频（热点/常规游戏向内容）",
    "durationText": "1-2min",
    "videoLengthType": "short",
    "benchmarkAccounts": "",
    "monthlyTarget": 4,
    "monthlyTotal": 0,
    "note": ""
  },
  {
    "groupName": "内容小组",
    "platform": "douyin",
    "accountType": "重点账号",
    "owner": "",
    "account": "报告砖家",
    "contentDirection": "非游热梗",
    "durationText": "1-2min",
    "videoLengthType": "short",
    "benchmarkAccounts": "",
    "monthlyTarget": 2,
    "monthlyTotal": 0,
    "note": ""
  },
  {
    "groupName": "内容小组",
    "platform": "douyin",
    "accountType": "重点账号",
    "owner": "",
    "account": "策划克星阿强",
    "contentDirection": "游戏深度体验/解说向",
    "durationText": "2-3min",
    "videoLengthType": "long",
    "benchmarkAccounts": "",
    "monthlyTarget": 2,
    "monthlyTotal": 10,
    "note": ""
  },
  {
    "groupName": "内容小组",
    "platform": "douyin",
    "accountType": "重点账号",
    "owner": "",
    "account": "策划克星阿强",
    "contentDirection": "短视频（热点/常规游戏向内容）",
    "durationText": "1-2min",
    "videoLengthType": "short",
    "benchmarkAccounts": "",
    "monthlyTarget": 6,
    "monthlyTotal": 0,
    "note": ""
  },
  {
    "groupName": "内容小组",
    "platform": "douyin",
    "accountType": "重点账号",
    "owner": "",
    "account": "策划克星阿强",
    "contentDirection": "非游热梗",
    "durationText": "1-2min",
    "videoLengthType": "short",
    "benchmarkAccounts": "",
    "monthlyTarget": 2,
    "monthlyTotal": 0,
    "note": ""
  },
  {
    "groupName": "内容小组",
    "platform": "douyin",
    "accountType": "重点账号",
    "owner": "",
    "account": "天机妹",
    "contentDirection": "短视频（常规游戏向内容）",
    "durationText": "1-2min",
    "videoLengthType": "short",
    "benchmarkAccounts": "",
    "monthlyTarget": 4,
    "monthlyTotal": 12,
    "note": ""
  },
  {
    "groupName": "内容小组",
    "platform": "douyin",
    "accountType": "重点账号",
    "owner": "",
    "account": "天机妹",
    "contentDirection": "短视频（热点）",
    "durationText": "20-60s",
    "videoLengthType": "short",
    "benchmarkAccounts": "",
    "monthlyTarget": 8,
    "monthlyTotal": 0,
    "note": ""
  },
  {
    "groupName": "内容小组",
    "platform": "douyin",
    "accountType": "重点账号",
    "owner": "",
    "account": "麦小雯",
    "contentDirection": "短视频（热点）",
    "durationText": "20-60s",
    "videoLengthType": "short",
    "benchmarkAccounts": "",
    "monthlyTarget": 4,
    "monthlyTotal": 12,
    "note": ""
  },
  {
    "groupName": "内容小组",
    "platform": "douyin",
    "accountType": "重点账号",
    "owner": "",
    "account": "麦小雯",
    "contentDirection": "短视频（常规游戏向内容）",
    "durationText": "1-2min",
    "videoLengthType": "short",
    "benchmarkAccounts": "",
    "monthlyTarget": 2,
    "monthlyTotal": 0,
    "note": ""
  },
  {
    "groupName": "内容小组",
    "platform": "douyin",
    "accountType": "重点账号",
    "owner": "",
    "account": "木游话说",
    "contentDirection": "游戏深度体验/解说向",
    "durationText": "2-3min",
    "videoLengthType": "long",
    "benchmarkAccounts": "",
    "monthlyTarget": 2,
    "monthlyTotal": 10,
    "note": ""
  },
  {
    "groupName": "内容小组",
    "platform": "douyin",
    "accountType": "重点账号",
    "owner": "",
    "account": "木游话说",
    "contentDirection": "短视频（热点/常规游戏向内容）",
    "durationText": "1-2min",
    "videoLengthType": "short",
    "benchmarkAccounts": "",
    "monthlyTarget": 6,
    "monthlyTotal": 0,
    "note": ""
  },
  {
    "groupName": "内容小组",
    "platform": "douyin",
    "accountType": "重点账号",
    "owner": "",
    "account": "木游话说",
    "contentDirection": "非游热梗",
    "durationText": "1-2min",
    "videoLengthType": "short",
    "benchmarkAccounts": "",
    "monthlyTarget": 2,
    "monthlyTotal": 0,
    "note": ""
  },
  {
    "groupName": "内容小组",
    "platform": "douyin",
    "accountType": "真人出镜",
    "owner": "",
    "account": "薛定谔的机",
    "contentDirection": "短视频（热点/常规游戏向内容）",
    "durationText": "1-2min",
    "videoLengthType": "short",
    "benchmarkAccounts": "",
    "monthlyTarget": 4,
    "monthlyTotal": 4,
    "note": ""
  },
  {
    "groupName": "内容小组",
    "platform": "douyin",
    "accountType": "真人出镜",
    "owner": "",
    "account": "葵仔不想肝",
    "contentDirection": "短视频（热点/常规游戏向内容）",
    "durationText": "1-2min",
    "videoLengthType": "short",
    "benchmarkAccounts": "",
    "monthlyTarget": 4,
    "monthlyTotal": 4,
    "note": ""
  },
  {
    "groupName": "内容小组",
    "platform": "douyin",
    "accountType": "文案解说",
    "owner": "",
    "account": "麦冬冬",
    "contentDirection": "游戏深度体验/解说向",
    "durationText": "3-5min",
    "videoLengthType": "long",
    "benchmarkAccounts": "",
    "monthlyTarget": 4,
    "monthlyTotal": 4,
    "note": ""
  },
  {
    "groupName": "内容小组",
    "platform": "douyin",
    "accountType": "文案解说",
    "owner": "",
    "account": "超玩教授",
    "contentDirection": "游戏深度体验/解说向",
    "durationText": "3-5min",
    "videoLengthType": "long",
    "benchmarkAccounts": "",
    "monthlyTarget": 4,
    "monthlyTotal": 4,
    "note": ""
  },
  {
    "groupName": "内容小组",
    "platform": "douyin",
    "accountType": "次重点账号",
    "owner": "",
    "account": "网瘾少女一条",
    "contentDirection": "短视频（热点/常规游戏向内容）;非游热梗",
    "durationText": "20-60s",
    "videoLengthType": "short",
    "benchmarkAccounts": "",
    "monthlyTarget": 10,
    "monthlyTotal": 10,
    "note": ""
  },
  {
    "groupName": "内容小组",
    "platform": "douyin",
    "accountType": "次重点账号",
    "owner": "",
    "account": "灵梦小师妹",
    "contentDirection": "短视频（热点/常规游戏向内容）;非游热梗",
    "durationText": "1-2min",
    "videoLengthType": "short",
    "benchmarkAccounts": "",
    "monthlyTarget": 6,
    "monthlyTotal": 6,
    "note": ""
  },
  {
    "groupName": "内容小组",
    "platform": "douyin",
    "accountType": "次重点账号",
    "owner": "",
    "account": "Lee小强",
    "contentDirection": "短视频（热点/常规游戏向内容）;非游热梗",
    "durationText": "1-2min",
    "videoLengthType": "short",
    "benchmarkAccounts": "",
    "monthlyTarget": 8,
    "monthlyTotal": 8,
    "note": ""
  },
  {
    "groupName": "内容小组",
    "platform": "douyin",
    "accountType": "次重点账号",
    "owner": "",
    "account": "游小妹",
    "contentDirection": "短视频（热点/常规游戏向内容）;非游热梗",
    "durationText": "1-2min",
    "videoLengthType": "short",
    "benchmarkAccounts": "",
    "monthlyTarget": 6,
    "monthlyTotal": 6,
    "note": ""
  },
  {
    "groupName": "内容小组",
    "platform": "douyin",
    "accountType": "次重点账号",
    "owner": "",
    "account": "游热娃子",
    "contentDirection": "短视频（热点/常规游戏向内容）;非游热梗",
    "durationText": "1-2min",
    "videoLengthType": "short",
    "benchmarkAccounts": "",
    "monthlyTarget": 6,
    "monthlyTotal": 6,
    "note": ""
  },
  {
    "groupName": "内容小组",
    "platform": "bilibili",
    "accountType": "",
    "owner": "",
    "account": "痞仔伯爵",
    "contentDirection": "商单+日常",
    "durationText": "4min+",
    "videoLengthType": "long",
    "benchmarkAccounts": "",
    "monthlyTarget": 4,
    "monthlyTotal": 4,
    "note": ""
  },
  {
    "groupName": "内容小组",
    "platform": "bilibili",
    "accountType": "",
    "owner": "",
    "account": "暴走星号键",
    "contentDirection": "",
    "durationText": "4min+",
    "videoLengthType": "long",
    "benchmarkAccounts": "",
    "monthlyTarget": 3,
    "monthlyTotal": 3,
    "note": ""
  },
  {
    "groupName": "内容小组",
    "platform": "bilibili",
    "accountType": "",
    "owner": "",
    "account": "雷鸭fist",
    "contentDirection": "",
    "durationText": "4min+",
    "videoLengthType": "long",
    "benchmarkAccounts": "",
    "monthlyTarget": 3,
    "monthlyTotal": 3,
    "note": ""
  },
  {
    "groupName": "内容小组",
    "platform": "bilibili",
    "accountType": "",
    "owner": "",
    "account": "跑腿的包子",
    "contentDirection": "",
    "durationText": "4min+",
    "videoLengthType": "long",
    "benchmarkAccounts": "",
    "monthlyTarget": 4,
    "monthlyTotal": 4,
    "note": ""
  },
  {
    "groupName": "内容小组",
    "platform": "bilibili",
    "accountType": "",
    "owner": "",
    "account": "中二探长",
    "contentDirection": "",
    "durationText": "4min+",
    "videoLengthType": "long",
    "benchmarkAccounts": "",
    "monthlyTarget": 2,
    "monthlyTotal": 2,
    "note": ""
  },
  {
    "groupName": "内容小组",
    "platform": "bilibili",
    "accountType": "",
    "owner": "",
    "account": "团子好贵",
    "contentDirection": "",
    "durationText": "4min+",
    "videoLengthType": "long",
    "benchmarkAccounts": "",
    "monthlyTarget": 3,
    "monthlyTotal": 3,
    "note": ""
  },
  {
    "groupName": "内容小组",
    "platform": "bilibili",
    "accountType": "",
    "owner": "",
    "account": "薛定谔的机",
    "contentDirection": "",
    "durationText": "4min+",
    "videoLengthType": "long",
    "benchmarkAccounts": "",
    "monthlyTarget": 3,
    "monthlyTotal": 3,
    "note": ""
  },
  {
    "groupName": "内容小组",
    "platform": "bilibili",
    "accountType": "",
    "owner": "",
    "account": "李野王SG",
    "contentDirection": "",
    "durationText": "4min+",
    "videoLengthType": "long",
    "benchmarkAccounts": "",
    "monthlyTarget": 3,
    "monthlyTotal": 3,
    "note": ""
  },
  {
    "groupName": "内容小组",
    "platform": "bilibili",
    "accountType": "",
    "owner": "",
    "account": "游电工厂",
    "contentDirection": "",
    "durationText": "4min+",
    "videoLengthType": "long",
    "benchmarkAccounts": "",
    "monthlyTarget": 3,
    "monthlyTotal": 3,
    "note": ""
  },
  {
    "groupName": "内容小组",
    "platform": "bilibili",
    "accountType": "",
    "owner": "",
    "account": "硬件侠",
    "contentDirection": "",
    "durationText": "4min+",
    "videoLengthType": "long",
    "benchmarkAccounts": "",
    "monthlyTarget": 3,
    "monthlyTotal": 3,
    "note": ""
  },
  {
    "groupName": "内容小组",
    "platform": "bilibili",
    "accountType": "",
    "owner": "",
    "account": "情风师兄",
    "contentDirection": "",
    "durationText": "4min+",
    "videoLengthType": "long",
    "benchmarkAccounts": "",
    "monthlyTarget": 3,
    "monthlyTotal": 3,
    "note": ""
  },
  {
    "groupName": "内容小组",
    "platform": "bilibili",
    "accountType": "",
    "owner": "",
    "account": "上官北丶",
    "contentDirection": "",
    "durationText": "4min+",
    "videoLengthType": "long",
    "benchmarkAccounts": "",
    "monthlyTarget": 3,
    "monthlyTotal": 3,
    "note": ""
  },
  {
    "groupName": "内容小组",
    "platform": "bilibili",
    "accountType": "",
    "owner": "",
    "account": "王路飞CP",
    "contentDirection": "",
    "durationText": "4min+",
    "videoLengthType": "long",
    "benchmarkAccounts": "",
    "monthlyTarget": 3,
    "monthlyTotal": 3,
    "note": ""
  }
]

export const updatePlanRows = rawUpdatePlanRows.map((row, index) => ({
  id: `update-plan-${index + 1}`,
  ...row,
  platformLabel: platformLabels[row.platform] || row.platform,
  monthlyTarget: Number(row.monthlyTarget) || 0,
  monthlyTotal: Number(row.monthlyTotal) || 0
}))
